class Message:
    def __init__(self):
        self.mapmsg = {}
        self.mapmsg[1] = "Runtime unexpected exception: '%s'"
        self.mapmsg[2] = "Configuration of the logging into file '%s' is starting"
        self.mapmsg[3] = "Task of kind '%s' with name '%s' is completed"
        self.mapmsg[4] = "Task of kind '%s' with name '%s' is starting"
        self.mapmsg[5] = "Configuration of the logging into file '%s' is completed"
        self.mapmsg[6] = "Error configuring the logging, check the security for file '%s'"
        self.mapmsg[7] = "The file '%s' needs read/write access"

        self.mapmsg[8] = "Query '%s' is starting"
        self.mapmsg[9] = "Query '%s' is completed"


        self.mapmsg[11] = "JSON: The connection' name '%s' at the position '%s' already exists"
        self.mapmsg[12] = "JSON: The connection at the position '%s' does not contains the field '%s'"

        self.mapmsg[26] = "JSON: The task at position '%s' does not contains the field '%s'"
        self.mapmsg[27] = "JSON: The task at position '%s' with the name '%s' does not contains the field '%s'"
        self.mapmsg[28] = "JSON: The task at position '%s' with the name '%s' does not support the OutputType: '%s'"
        self.mapmsg[29] = "JSON: The supported OutputType is <memory> only"
        self.mapmsg[32] = "JSON: the parameter at position '%s' of the task at position '%s' does not contains the field <%>"

        self.mapmsg[40] = "The property value must be an array, not a single value"
        self.mapmsg[41] = "Curl error: "
        
        self.mapmsg[56] = "Pyarchive started"
        self.mapmsg[57] = "Pyarchive completed with success"

        # curl returncode error from documentation 7.82
        self.mapmsg[501] = "Unsupported protocol. This build of curl has no support for this protocol"
        self.mapmsg[502] = "Failed to initialize"
        self.mapmsg[503] = "URL malformed. The syntax was not correct."
        self.mapmsg[504] = "A feature or option that was needed to perform the desired request was not enabled or was explicitly disabled at build-time. To make curl able to do this, you probably need another build of libcurl."
        self.mapmsg[505] = "Could not resolve proxy. The given proxy host could not be resolved."
        self.mapmsg[506] = "Could not resolve host. The given remote host could not be resolved."
        self.mapmsg[507] = "Failed to connect to host."
        self.mapmsg[508] = "Weird server reply. The server sent data curl could not parse."
        self.mapmsg[509] = "FTP access denied. The server denied login or denied access to the particular resource or directory you wanted to reach. Most often you tried to change to a directory that does not exist on the server."
        self.mapmsg[510] = "FTP accept failed. While waiting for the server to connect back when an active FTP session is used, an error code was sent over the control connection or similar."
        self.mapmsg[511] = "FTP weird PASS reply. Curl could not parse the reply sent to the PASS request."
        self.mapmsg[512] = "During an active FTP session while waiting for the server to connect back to curl, the timeout expired."
        self.mapmsg[513] = "FTP weird PASV reply, Curl could not parse the reply sent to the PASV request."
        self.mapmsg[514] = "FTP weird 227 format. Curl could not parse the 227-line the server sent."
        self.mapmsg[515] = "FTP cannot use host. Could not resolve the host IP we got in the 227-line."
        self.mapmsg[516] = "HTTP/2 error. A problem was detected in the HTTP2 framing layer. This is somewhat generic and can be one out of several problems, see the error message for details."
        self.mapmsg[517] = "FTP could not set binary. Could not change transfer method to binary."
        self.mapmsg[518] = "Partial file. Only a part of the file was transferred."
        self.mapmsg[519] = "FTP could not download/access the given file, the RETR (or similar) command failed."
        self.mapmsg[521] = "FTP quote error. A quote command returned error from the server."
        self.mapmsg[522] = "HTTP page not retrieved. The requested url was not found or returned another error with the HTTP error code being 400 or above. This return code only appears if --fail is used."
        self.mapmsg[523] = "Write error. Curl could not write data to a local filesystem or similar."
        self.mapmsg[525] = "FTP could not STOR file. The server denied the STOR operation, used for FTP uploading."
        self.mapmsg[526] = "Read error. Various reading problems."
        self.mapmsg[527] = "Out of memory. A memory allocation request failed."
        self.mapmsg[528] = "Operation timeout. The specified time-out period was reached according to the conditions."
        self.mapmsg[530] = "FTP PORT failed. The PORT command failed. Not all FTP servers support the PORT command, try doing a transfer using PASV instead!"
        self.mapmsg[531] = "FTP could not use REST. The REST command failed. This command is used for resumed FTP transfers."
        self.mapmsg[533] = "HTTP range error. The range 'command' did not work."
        self.mapmsg[534] = "HTTP post error. Internal post-request generation error."
        self.mapmsg[535] = "SSL connect error. The SSL handshaking failed."
        self.mapmsg[536] = "Bad download resume. Could not continue an earlier aborted download."
        self.mapmsg[537] = "FILE could not read file. Failed to open the file. Permissions?"
        self.mapmsg[538] = "LDAP cannot bind. LDAP bind operation failed."
        self.mapmsg[539] = "LDAP search failed."
        self.mapmsg[541] = "Function not found. A required LDAP function was not found."
        self.mapmsg[542] = "Aborted by callback. An application told curl to abort the operation."
        self.mapmsg[543] = "Internal error. A function was called with a bad parameter."
        self.mapmsg[545] = "Interface error. A specified outgoing interface could not be used."
        self.mapmsg[547] = "Too many redirects. When following redirects, curl hit the maximum amount."
        self.mapmsg[548] = "Unknown option specified to libcurl. This indicates that you passed a weird option to curl that was passed on to libcurl and rejected. Read up in the manual!"
        self.mapmsg[549] = "Malformed telnet option."
        self.mapmsg[551] = "The peer's SSL certificate or SSH MD5 fingerprint was not OK."
        self.mapmsg[552] = "The server did not reply anything, which here is considered an error."
        self.mapmsg[553] = "SSL crypto engine not found."
        self.mapmsg[554] = "Cannot set SSL crypto engine as default."
        self.mapmsg[555] = "Failed sending network data."
        self.mapmsg[556] = "Failure in receiving network data."
        self.mapmsg[558] = "Problem with the local certificate."
        self.mapmsg[559] = "Could not use specified SSL cipher."
        self.mapmsg[560] = "Peer certificate cannot be authenticated with known CA certificates."
        self.mapmsg[561] = "Unrecognized transfer encoding."
        self.mapmsg[562] = "Invalid LDAP URL."
        self.mapmsg[563] = "Maximum file size exceeded."
        self.mapmsg[564] = "Requested FTP SSL level failed."
        self.mapmsg[565] = "Sending the data requires a rewind that failed."
        self.mapmsg[566] = "Failed to initialise SSL Engine."
        self.mapmsg[567] = "The user name, password, or similar was not accepted and curl failed to log in."
        self.mapmsg[568] = "File not found on TFTP server."
        self.mapmsg[569] = "Permission problem on TFTP server."
        self.mapmsg[570] = "Out of disk space on TFTP server."
        self.mapmsg[571] = "Illegal TFTP operation."
        self.mapmsg[572] = "Unknown TFTP transfer ID."
        self.mapmsg[573] = "File already exists (TFTP)."
        self.mapmsg[574] = "No such user (TFTP)."
        self.mapmsg[575] = "Character conversion failed."
        self.mapmsg[576] = "Character conversion functions required."
        self.mapmsg[577] = "Problem reading the SSL CA cert (path? access rights?)."
        self.mapmsg[578] = "The resource referenced in the URL does not exist."
        self.mapmsg[579] = "An unspecified error occurred during the SSH session."
        self.mapmsg[580] = "Failed to shut down the SSL connection."
        self.mapmsg[582] = "Could not load CRL file, missing or wrong format."
        self.mapmsg[583] = "Issuer check failed."
        self.mapmsg[584] = "The FTP PRET command failed."
        self.mapmsg[585] = "Mismatch of RTSP CSeq numbers."
        self.mapmsg[586] = "Mismatch of RTSP Session Identifiers."
        self.mapmsg[587] = "Unable to parse FTP file list."
        self.mapmsg[588] = "FTP chunk callback reported error."
        self.mapmsg[589] = "No connection available, the session will be queued."
        self.mapmsg[590] = "SSL public key does not matched pinned public key."
        self.mapmsg[591] = "Invalid SSL certificate status."
        self.mapmsg[592] = "Stream error in HTTP/2 framing layer."
        self.mapmsg[593] = "An API function was called from inside a callback."
        self.mapmsg[594] = "An authentication function returned an error."
        self.mapmsg[595] = "A problem was detected in the HTTP/3 layer. This is somewhat generic and can be one out of several problems, see the error message for details."
        self.mapmsg[596] = "QUIC connection error. This error may be caused by an SSL library error. QUIC is the protocol used for HTTP/3 transfers."
        self.mapmsg[599] = "Curl unknown error."
    #def

    def get(self,id):
        return  "Msg#:{id}:{msg}".format(id = id, msg = self.mapmsg[id])
    #def
#class

gmsg = Message()